FROM node:lts-bookworm

ARG LATEST_TAG
WORKDIR /opt/mcsmanager/daemon

RUN cd /tmp && \
    wget -O /tmp/mcsmanager.tar.gz https://github.com/MCSManager/MCSManager/releases/download/$LATEST_TAG/mcsmanager_linux_release.tar.gz && \
    tar -xf mcsmanager.tar.gz && \
    mv /tmp/mcsmanager/daemon/* /opt/mcsmanager/daemon && \
    cd /opt/mcsmanager/daemon && \
    npm install --production --no-fund --no-audit && \
    rm -rf /tmp/*

ENTRYPOINT ["node", "app.js", "--max-old-space-size=8192"]