FROM node:lts-alpine as builder
RUN apk update && \
    apk --no-cache add --virtual .build-deps wget && \
    cd /opt && \
    wget https://github.com/MCSManager/MCSManager/releases/latest/download/mcsmanager_linux_release.tar.gz && \
    tar -zxf mcsmanager_linux_release.tar.gz && \
    rm -rf mcsmanager_linux_release.tar.gz && \
    apk del .build-deps

FROM node:lts-alpine
WORKDIR /opt/mcsmanager/web
COPY --from=builder /opt/web ./
RUN npm install --production
ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
ENTRYPOINT ["node", "app.js", "--max-old-space-size=8192"]