FROM node:lts-alpine

ARG LATEST_TAG
WORKDIR /opt/mcsmanager/web

RUN cd /tmp && \
    wget -O /tmp/mcsmanager.tar.gz https://github.com/MCSManager/MCSManager/releases/download/$LATEST_TAG/mcsmanager_linux_release.tar.gz && \
    tar -xf mcsmanager.tar.gz && \
    mv /tmp/mcsmanager/web/* /opt/mcsmanager/web && \
    cd /opt/mcsmanager/web && \
    npm install --production && \
    rm -rf /tmp/*

ENTRYPOINT ["node", "app.js", "--max-old-space-size=8192"]