name: Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ilkeiii
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push daemon
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.daemon
          push: true # push to docker hub
          tags: |
              ilkeiii/mcsmanager-daemon:latest
          platforms: linux/amd64

      - name: Build and push web
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.web
          push: true # push to docker hub
          tags: |
              ilkeiii/mcsmanager-web:latest
          platforms: linux/amd64