name: Docker images build and push

on:
  push:
    branches: [ "main" ]
    paths:
      - 'actions-time.txt'
  # schedule:
    # - cron: "0 0 12 * *"   # 每天12点

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: 1lkei
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build-push daemon
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.daemon
          push: true # push to docker hub
          tags: |
              1lkei/mcsmanager-daemon:latest
          platforms: linux/amd64,linux/arm64

      - name: Docker build-push debian_daemon
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile_debian.daemon
          push: true # push to docker hub
          tags: |
              1lkei/mcsmanager-daemon:debian
          platforms: linux/amd64,linux/arm64

      - name: Docker build-push web
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.web
          push: true # push to docker hub
          tags: |
              1lkei/mcsmanager-web:latest
          platforms: linux/amd64,linux/arm64