name: Docker images auto build and push

on:
  schedule:
    - cron: "0 0 * * *"   # 每天12点

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Get latest release version
        run: | 
          latest_version=$(curl -s https://api.github.com/repos/MCSManager/MCSManager/releases/latest | jq -r .tag_name)
          echo "latest_version=$latest_version" >> $GITHUB_ENV

      - name: Check local version
        run: |
          if [ -f ./MCSManager_version ]; then
            local_version=$(cat ./MCSManager_version)
          else
            local_version="none"
          fi
          echo "local_version=$local_version" >> $GITHUB_ENV

      - name: Set up QEMU
        if: env.local_version != env.latest_version
        uses: docker/setup-qemu-action@v3.2.0

      - name: Set up Docker Buildx
        if: env.local_version != env.latest_version
        uses: docker/setup-buildx-action@v3.7.1

      - name: Login to DockerHub
        if: env.local_version != env.latest_version
        uses: docker/login-action@v3.3.0
        with:
          username: 1lkei
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build-push daemon
        if: env.local_version != env.latest_version
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          file: Dockerfile.daemon
          push: true # push to docker hub
          tags: |
            1lkei/mcsmanager-daemon:latest
            1lkei/mcsmanager-daemon:${{ env.latest_version }}
          build-args: |
            LATEST_TAG=${{ env.latest_version }}
          platforms: linux/amd64,linux/arm64

      - name: Docker build-push daemon_debian
        if: env.local_version != env.latest_version
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          file: Dockerfile.daemon_debian
          push: true # push to docker hub
          tags: |
              1lkei/mcsmanager-daemon:debian
              1lkei/mcsmanager-daemon:debian-${{ env.latest_version }}
          build-args: |
            LATEST_TAG=${{ env.latest_version }}
          platforms: linux/amd64,linux/arm64

      - name: Docker build-push web
        if: env.local_version != env.latest_version
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          file: Dockerfile.web
          push: true # push to docker hub
          tags: |
              1lkei/mcsmanager-web:latest
              1lkei/mcsmanager-web:${{ env.latest_version }}
          build-args: |
            LATEST_TAG=${{ env.latest_version }}
          platforms: linux/amd64,linux/arm64

      - name: Docker build-push aio
        if: env.local_version != env.latest_version
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          file: Dockerfile.aio
          push: true # push to docker hub
          tags: |
              1lkei/mcsmanager:latest
              1lkei/mcsmanager:${{ env.latest_version }}
          build-args: |
            LATEST_TAG=${{ env.latest_version }}
          platforms: linux/amd64,linux/arm64

      - name: Commit updated version
        if: env.local_version != env.latest_version
        run: |
          echo "$latest_version" > MCSManager_version
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add MCSManager_version
          git commit -m "Update version to $latest_version"
          git remote set-url origin https://1lkei:${{ secrets.REPO_BOT }}@github.com/1lkei/mcsmanager-docker.git
          git push